### ISSUE TITLE
Changed "markdown.preview.fontSize" but no effect on the preview tab. How to decrease previewed font size?

### ISSUE THREAD

**Issue by carloscadux** [mjbvz/vscode-github-markdown-preview-style#86] opened 2022-03-04 12:26 UTC
Hi. I'd appreciate your help.

I changed VSCode setting 'markdown.preview.fontSize' expecting the font previewed by 'Markdown Preview Github Styling' would change (currently too big). But no effect.
Should 'markdown.preview.fontSize' affect 'Markdown Preview Github Styling' font size?
How to decrease previewed font size in 'Markdown Preview Github Styling'?

Thank you!

**Comment by mjbvz** [comment] 2022-03-04 19:03
Duplicate of #30

**Closed by mjbvz** 2022-03-04 19:03 UTC
