### ISSUE TITLE
Add Callout Feature

### ISSUE THREAD

**Issue by Harxxki** [mjbvz/vscode-github-markdown-preview-style#122] opened 2023-10-17 04:32 UTC
I'd like to express my interest in having the "callout" feature, which is available in GitHub Flavored Markdown, to be incorporated into the VSCode markdown preview.

**callout example**

Code

```
> [!NOTE]  
> Highlights information that users should take into account, even when skimming.

> [!IMPORTANT]  
> Crucial information necessary for users to succeed.

> [!WARNING]  
> Critical content demanding immediate user attention due to potential risks.
```

Output

> [!NOTE]  
> Highlights information that users should take into account, even when skimming.

> [!IMPORTANT]  
> Crucial information necessary for users to succeed.

> [!WARNING]  
> Critical content demanding immediate user attention due to potential risks.

**Comment by jjspace** [comment] 2023-10-17 13:25
Duplicate of https://github.com/mjbvz/vscode-github-markdown-preview/issues/23

**Comment by mjbvz** [comment] 2023-10-17 23:45
Closing as duplicate

Please make sure to search before opening an issue: https://github.com/mjbvz/vscode-github-markdown-preview-style/issues?q=is%3Aissue+NOTE+is%3Aclosed

**Closed by mjbvz** 2023-10-17 23:45 UTC
Labels: duplicate
