### ISSUE TITLE
No white bg in body

### ISSUE THREAD

**Issue by elrumordelaluz** [mjbvz/vscode-github-markdown-preview-style#35] opened 2018-10-18 15:31 UTC
Is there a reason why after install and activate the _extension_ and opening `Open Webvie Developer Tools`, the `body` is:

```css
body {
  background-color: var(--vscode-editor-background);
  /* ... */
}
```

**Comment by elrumordelaluz** [comment] 2018-10-23 07:41
There's no evidence of _errors_, the issue is that after install and activate, the _preview_ remains with the _editor background_. Following a demo:

![markdown](https://user-images.githubusercontent.com/784056/47344002-aa4f3400-d6a7-11e8-90db-72e4c83f7f85.gif)

and inspecting

![markdown_2](https://user-images.githubusercontent.com/784056/47344008-b0ddab80-d6a7-11e8-9e44-ae9e0f39108e.gif)

**Comment by mjbvz** [comment] 2018-10-23 18:36
It doesn't look the the extension is even loading. In the webview, can you verify that the `<link>` stylesheet import for this extension is in the `head`?  Also, do you have any other markdown extension installed?

**Comment by elrumordelaluz** [comment] 2018-10-23 21:17
no `<link>` in `head` and I haven't installed other md-related _extensions_.

However disabled all _extensions_ and reinstalled _Markdown Preview Github Styling_ but stills the same result.

![screen shot 2018-10-23 at 23 13 21](https://user-images.githubusercontent.com/784056/47391227-8e847600-d719-11e8-87de-1e725d35b718.png)

**Comment by elrumordelaluz** [comment] 2018-10-26 19:58
[update]

there are `<link>`s in `head` but for some reason _styles_ doesn't apply in DOM nodes.

<img width="1552" alt="screen shot 2018-10-26 at 21 56 38" src="https://user-images.githubusercontent.com/784056/47589646-0a74fd00-d96a-11e8-8886-f1de6456452a.png">

`body` only have _styles_ applied from `<style>` tag with default _editor styles_

**Comment by Gliptal** [comment] 2018-11-05 20:16
I seem to be having the same problem. No white background, default styling.

**Comment by mjbvz** [comment] 2018-11-12 23:05
Likely a duplicate of #40. Do you have `files.associations` set?

**Comment by Gliptal** [comment] 2018-11-12 23:10
Unfortunately I do not.

**Comment by mjbvz** [comment] 2019-04-03 18:20
Fixed upstream in VS Code

**Closed by mjbvz** 2019-04-03 18:20 UTC
