### ISSUE TITLE
Do not work anymore on VS Code 1.21.0

### ISSUE THREAD

**Issue by paulbombarde** [mjbvz/vscode-github-markdown-preview-style#17] opened 2018-03-08 13:58 UTC
Hello,

I updated VS code today (March 03 2018), and now the md preview is it raw form :(
I tried various basic things like install/uninstall the extension without success.

Version 1.21.0
Commit 9a199d77c82fcb82f39c68bb33c614af01c111ba
Date 2018-03-07T11:04:09.969Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by mjbvz** [comment] 2018-03-08 19:12
Duplicate of #15

**Closed by mjbvz** 2018-03-08 19:12 UTC

**Comment by paulbombarde** [comment] 2018-03-15 17:38
Confirmed to be now working on 1.21.1. Thanks !

Version 1.21.1
Commit 79b44aa704ce542d8ca4a3cc44cfca566e7720f1
Date 2018-03-14T14:46:47.128Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
