### ISSUE TITLE
Extension no longer work in VS Code 1.21.0

### ISSUE THREAD

**Issue by benc-uk** [mjbvz/vscode-github-markdown-preview-style#16] opened 2018-03-08 09:00 UTC
The extension no longer works since updating VS Code to 1.21.
The preview window is shown in the default style (in my case dark) and not with GitHub styling.

I can see no errors in the output logs or the dev console

**Comment by mjbvz** [comment] 2018-03-08 09:06
Duplicate of #15

**Closed by mjbvz** 2018-03-08 09:06 UTC

**Comment by benc-uk** [comment] 2018-03-08 09:08
Ok looks like a issue with vs code itself. That's a shame. I'll wait for a fix
