### ISSUE TITLE
[Bug] GitHub "Alert" Syntax Formatting Problem

### ISSUE THREAD

**Issue by 1chooo** [mjbvz/vscode-github-markdown-preview-style#137] opened 2024-06-10 05:54 UTC
### Issue with GitHub "Alert" Syntax in New Markdown Preview

While using this extension, the GitHub "alert" syntax experiences formatting issues during rendering, as demonstrated in the video below. This requires some adjustments. Despite this, the extension is a great solution to address my issue https://github.com/microsoft/vscode/issues/214732 in VSCode. 

https://github.com/mjbvz/vscode-github-markdown-preview-style/assets/94162591/74fabdcb-f005-43fb-bb0f-57a3d22c4269

Expected:

![Screenshot 2024-06-10 at 1 52 22 PM](https://github.com/mjbvz/vscode-github-markdown-preview-style/assets/94162591/5855db5e-16b4-440d-bc4b-ac7255250030)

The current effect:

![Screenshot 2024-06-10 at 1 52 38 PM](https://github.com/mjbvz/vscode-github-markdown-preview-style/assets/94162591/2c15215f-0287-421d-85a7-437d9c14f115)

Thanks a lot!!!

**Comment by jjspace** [comment] 2024-06-10 14:53
Duplicate of #135 and #134. Alerts are not supported in this extension, it's a bug with the other one that adds them

**Comment by 1chooo** [comment] 2024-06-10 14:56
> Duplicate of #135 and #134. Alerts are not supported in this extension, it's a bug with the other one that adds them

Sorry for the duplicated Issue, do I have to close this issue?

**Comment by JSanchezIO** [comment] 2024-06-24 02:24
I know this has been brought up before, but I don't believe the error is due to the other mentioned extensions. Namely, this extension provides the GitHub styles using `generate-github-markdown-css` which had a bug in `6.2.0` that omitted the definition of the `--base-size-8` and `--base-size-16` CSS variables. Those variables are referenced in the _alert extensions_  to style the alerts. Based on that, I'm assuming that if we updated the `generate-github-markdown-css` dependency and published a new patch version these other extensions should render as expected.

**Comment by davearel** [comment] 2024-08-19 20:19
Yes please! VS Code's built-in markdown preview renders alerts, but then this addon breaks the styling. Would be nice to match githubs rendering. @JSanchezIO fix seems simple enough?

https://github.blog/changelog/2023-12-14-new-markdown-extension-alerts-provide-distinctive-styling-for-significant-content/

**Comment by jjspace** [comment] 2024-08-20 15:27
> VS Code's built-in markdown preview renders alerts

@davearel This is incorrect, VSCode does _not_ render alerts without a separate extension that adds support for this. You can verify this by running `code --disable-extensions` to see what VSCode does "out of the box".  If you want it added in VSCode by default (even though it shouldn't be) follow this issue: https://github.com/microsoft/vscode/issues/209652.

That said the style issue should be fixed by #141

**Closed** 2024-09-17 15:17 UTC
