### ISSUE TITLE
Alerts missing

### ISSUE THREAD

**Issue by trent-abc** [mjbvz/vscode-github-markdown-preview-style#144] opened 2024-11-06 00:41 UTC
Alerts are neat! and missing :(

https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts

**Comment by mjbvz** [comment] 2024-11-06 19:13
Duplicate of #125

**Closed by mjbvz** 2024-11-06 19:13 UTC
