### ISSUE TITLE
Text color changes to light grey with dark theme

### ISSUE THREAD

**Issue by BaerMitUmlaut** [mjbvz/vscode-github-markdown-preview-style#48] opened 2019-07-01 11:23 UTC
When you use a dark theme, the text color changes to a light gray and it gets quite unreadable:

![grafik](https://user-images.githubusercontent.com/9693842/60432729-4819dc00-9c03-11e9-8106-f5eb3f771c48.png)

**Comment by mjbvz** [comment] 2019-07-01 15:33
I can't repo. What is the markdown source?

<img width="797" alt="Screen Shot 2019-07-01 at 8 33 32 AM" src="https://user-images.githubusercontent.com/12821956/60448668-ef364d80-9bda-11e9-91f0-590bc67fcb4d.png">

**Comment by dlferro** [comment] 2020-04-03 16:49
I have this occurring as well. It appears to occur with all dark themes. In this example I'm using **Material Dark**.
![Screen Shot 2020-04-03 at 12 49 25 PM](https://user-images.githubusercontent.com/552068/78385274-99e3fe00-75a9-11ea-8741-92dbbcaddd04.png)

**Comment by jcolsen** [comment] 2020-05-09 22:14
I'm having the same problem, except for me it doesn't matter what theme I'm using. Light or dark theme, official or custom, headers are light grey. 

Using Visual Studio Code 1.45.0

**Comment by dschox** [comment] 2020-05-12 10:01
same as @jcolsen

**Comment by mjbvz** [comment] 2020-05-12 17:21
If you are seeing this recently, it is probably coming from another one of your extensions: https://github.com/Binaryify/OneDark-Pro/issues/391

**Comment by jcolsen** [comment] 2020-05-12 17:36
> If you are seeing this recently, it is probably coming from another one of your extensions: [Binaryify/OneDark-Pro#391](https://github.com/Binaryify/OneDark-Pro/issues/391)

You're right, it's being caused by that theme. I've disabled it until fixed. Thank you!

**Comment by mjbvz** [comment] 2020-05-12 20:58
I suspect the original problem reported may also have been caused by another extension or by some custom user styles

Closing but let me know if you find steps to reproduce

**Closed by mjbvz** 2020-05-12 20:58 UTC

**Comment by lumaxis** [comment] 2020-05-12 20:59
Looks like the [GitHub theme](https://github.com/primer/github-vscode-theme) is causing this too

**Comment by lumaxis** [comment] 2020-05-12 21:13
Ooh, looking at https://github.com/Binaryify/OneDark-Pro/issues/391, it sounds like what @mjbvz is saying is that simply having One Dark Pro _installed_ causes this? 😳

**Comment by Binaryify** [comment] 2020-05-13 03:31
@lumaxis that should already been fixed

**Comment by jcolsen** [comment] 2020-05-13 07:24
> @lumaxis that should already been fixed

The issue still persists with v3.5.5 for me if that's where the fix is applied.

**Comment by Binaryify** [comment] 2020-05-13 07:49
@jcolsen check v3.6.0

**Comment by PrivacyFriendlyMuffins** [comment] 2025-03-05 06:49
So, I'm having this problem too.

I don't have any custom userstyles. Also, this issue does not occur with light themes, but it does occur with One Dark Pro, as well as *every* other preinstalled dark theme that comes with VSCodium.

Uninstalling One Dark Pro doesn't fix the issue.

---

**VSCodium Version**: 1.97.2
**One Dark Pro Version**: 3.19.0
**Operating System**: Linux Mint 22.1 Cinnamon
