### ISSUE TITLE
Does not work in VSCode 1.21.0-insider

### ISSUE THREAD

**Issue by borekb** [mjbvz/vscode-github-markdown-preview-style#15] opened 2018-03-07 14:33 UTC
I happily use this extension in my main VSCode instance but now when I installed it to VSCode Insiders, I don't see any effect of it: the preview is still black, as per VSCode default. 

Version info:

```
Version 1.21.0-insider
Commit a903bd38fbe9006c076d218ff69fe1ee0160f815
Date 2018-03-06T11:09:37.589Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

**Comment by mjbvz** [comment] 2018-03-07 23:45
Duplicate of https://github.com/Microsoft/vscode/issues/45007 . Will try getting the fix into the vscode  1.21.1 build

**Closed by mjbvz** 2018-03-07 23:45 UTC
