### ISSUE TITLE
Add support for alerts

### ISSUE THREAD

**Issue by ookami-kb** [mjbvz/vscode-github-markdown-preview-style#112] opened 2023-08-09 12:17 UTC
GitHub recently added support for [alerts](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts).

E.g. this code:

```md
> [!NOTE]
> Highlights information that users should take into account, even when skimming.
```

will be rendered as

> [!NOTE]
> Highlights information that users should take into account, even when skimming.

**Comment by mjbvz** [comment] 2023-08-09 17:33
Duplicate of https://github.com/mjbvz/vscode-github-markdown-preview/issues/23

**Closed by mjbvz** 2023-08-09 17:33 UTC

**Comment by ookami-kb** [comment] 2023-08-09 17:47
Ah, was looking for `alert` issue, and didn't find anything. Thanks!
